# Generated by Django 4.2.1 on 2023-12-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ticker', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField(max_length=512)),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('P', 'Periodic Disclosure'), ('A', 'Annual Report'), ('E', 'Extension'), ('A', 'Amendment')], max_length=2)),
                ('related', models.ManyToManyField(help_text='Useful to relate amendments to the original disclosure', to='tracker.disclosure')),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('party', models.CharField(choices=[('D', 'Democratic'), ('R', 'Republican'), ('I', 'Independent')], max_length=2)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('owner', models.CharField(choices=[('S', 'Self'), ('SP', 'Spouse'), ('J', 'Joint')], max_length=2)),
                ('type', models.CharField(choices=[], max_length=2)),
                ('asset_type', models.CharField(choices=[('S', 'Stock')], max_length=2)),
                ('comment', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.asset')),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.disclosure')),
                ('senator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.senator')),
            ],
        ),
        migrations.AddField(
            model_name='disclosure',
            name='senator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.senator'),
        ),
    ]
