# Generated by Django 4.2.1 on 2023-12-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='scanned',
            field=models.BooleanField(default=False, help_text='Is a scan of a paper disclosure'),
        ),
    ]
